"""empty message

Revision ID: 2e715bf6ba63
Revises: 6694e81cab02
Create Date: 2022-08-25 19:14:01.933210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e715bf6ba63'
down_revision = '6694e81cab02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='flask_blog'
    )
    op.create_table('blog_posts_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('subtitle', sa.String(length=250), nullable=False),
    sa.Column('date', sa.String(length=1000), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['flask_blog.user_final.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    schema='flask_blog'
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commenter_id', sa.Integer(), nullable=True),
    sa.Column('comment_of_post', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['comment_of_post'], ['flask_blog.blog_posts_final.id'], ),
    sa.ForeignKeyConstraint(['commenter_id'], ['flask_blog.user_final.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='flask_blog'
    )
    op.drop_table('blog_user')
    op.drop_table('blog_posts')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment_author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_author_id'], ['blog_user.id'], name='comments_comment_author_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name='comments_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=450), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_user.id'], name='blog_posts_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_posts_pkey'),
    sa.UniqueConstraint('title', name='blog_posts_title_key')
    )
    op.create_table('blog_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blog_user_pkey'),
    sa.UniqueConstraint('email', name='blog_user_email_key')
    )
    op.drop_table('comments', schema='flask_blog')
    op.drop_table('blog_posts_final', schema='flask_blog')
    op.drop_table('user_final', schema='flask_blog')
    # ### end Alembic commands ###
